version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trainingplatform_postgres
    environment:
      POSTGRES_DB: trainingplatformdb
      POSTGRES_USER: trainingplatform_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1
    container_name: trainingplatform_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: