version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trainingplatform_postgres
    environment:
      POSTGRES_DB: trainingplatformdb
      POSTGRES_USER: trainingplatform_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1
    container_name: trainingplatform_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainingplatform_backend
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORD_DB: ${PASSWORD_DB}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: