spring:
  security:
    jwt:
      secret-key: f55c0f524cdc84303291192aacc46d5a86f1a259087a06e0ece82d0b754eeb7d
      expiration: 3600000 # an hour
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingplatformdb
    username: trainingplatform_user
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never