spring:
  application:
    name: training-platform
  cache:
    type: none
  data:
    redis:
      port: 6379
  security:
    jwt:
      expiration: 3600000 # an hour
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always